CREATE DATABASE IF NOT EXISTS luc;
USE luc;
CREATE TABLE IF NOT EXISTS usuario (
    usuario_id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS conta (
    conta_id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT,
    FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON UPDATE RESTRICT ON DELETE CASCADE
)  ENGINE=INNODB;